### PR TITLE
Fix code mismatch in directory names && Remove output files from repo

### PR DESCRIPTION
**Pull request by Nebrethar**
I'm doing my first-run of this software. This is the trace I found when I ran `findissues.js` as-is:
```
***INFO: Input:  /home/{REDACTED}/mariner/Mariner-Issue-Collector/inputFiles/inputData.json
***INFO: Output: /home/{REDACTED}/mariner/Mariner-Issue-Collector/outputFiles/outputData.json
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/{REDACTED}/mariner/Mariner-Issue-Collector/inputFiles/inputData.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/{REDACTED}/mariner/Mariner-Issue-Collector/findIssues.js:38:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```
I had to change the capitalization on the directories in order to get the file to work 😁 This is small but it makes a difference!

### CODE REVIEW

**Comment by Nebrethar** [comment]
Closing because I will be working on another issue with this

**Comment by Nebrethar** [comment]
Reopening! The next issue will take some time, so I might as well leave this here for now :)

**Comment by DuaneOBrien** [comment]
Hi Matt, good to see you. Nice catch on the case for the directory names, I thought I'd caught all those.

Re: the OutputFiles - I have those checked in by design, so that folks can see the app run with live data. Can I ask you to revert the commits where you delete the output files?

**Comment by DuaneOBrien** [comment]
Whuups, thought you were done.

**Comment by Nebrethar** [comment]
Hi @DuaneOBrien. You merged this as I was writing it :)

I wanted to note that this PR looks very messy for a simple change and I want to apologize for that. I was pretty much done, I think I ran into a newline issue but it was pretty much fixed!

**Comment by Nebrethar** [comment]
I'll look around for other things, but please let me know if you need help with anything else!

**Comment by DuaneOBrien** [comment]
No worries, I squashed it and that cleaned it up. My bad on the mid-authoring merge. I got a little click-happy there.

**Comment by DuaneOBrien** [comment]
@Nebrethar if you're interested in additional Hacktoberfest swag, you're invited to submit this form and we'll send you a shirt. https://docs.google.com/forms/d/e/1FAIpQLSeUKDE1fdyG3jRBngj0dnAXIEKscO128rrXw3a1BcFwNQ6iHg/viewform details at https://engineering.indeedblog.com/indeed-hacktoberfest-2020/

**Comment by Nebrethar** [comment]
@DuaneOBrien Thanks for the additional info :) I only submitted this PR because I ran into this issue when running Mariner. I am not participating specifically in Hacktoberfest, but I am interested in helping longer-term. I'll DM you on tw since I do not have your email :) but let me know if you have a more preferred method of contact outside of that!

**Pull request merged**
